# Generated by Django 4.2.7 on 2023-11-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("voice", models.CharField(max_length=255)),
                ("is_player", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
            },
        ),
        migrations.CreateModel(
            name="CharacterInteraction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_receptions",
                        to="narrator.character",
                    ),
                ),
                (
                    "transmitter_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_transmissions",
                        to="narrator.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction",
                "verbose_name_plural": "Interactions",
            },
        ),
        migrations.AddField(
            model_name="character",
            name="interactions",
            field=models.ManyToManyField(
                related_name="characters",
                through="narrator.CharacterInteraction",
                to="narrator.character",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="resources",
            field=models.ManyToManyField(
                related_name="characters", to="narrator.resource"
            ),
        ),
    ]
