# Generated by Django 4.2.7 on 2023-11-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterinteraction",
            name="text",
            field=models.TextField(default="DUMMY"),
            preserve_default=False,
        ),
    ]
