# Generated by Django 4.2.7 on 2023-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0002_characterinteraction_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="interactions",
        ),
        migrations.AlterField(
            model_name="character",
            name="voice",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
