# Generated by Django 4.2.7 on 2023-11-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0003_remove_character_interactions_alter_character_voice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterThread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_reception_threads",
                        to="narrator.character",
                    ),
                ),
                (
                    "transmitter_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_transmission_threads",
                        to="narrator.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
            },
        ),
    ]
