# Generated by Django 4.2.7 on 2023-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0004_characterthread"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="characterthread",
            index=models.Index(
                fields=["thread_id"], name="narrator_ch_thread__42e346_idx"
            ),
        ),
    ]
