# Generated by Django 4.2.7 on 2023-11-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0006_campaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
    ]
