# Generated by Django 4.2.7 on 2023-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0007_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(),
        ),
    ]
