# Generated by Django 4.2.7 on 2024-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0008_alter_campaign_description_alter_place_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="specs",
            field=models.FileField(null=True, upload_to="uploads"),
        ),
    ]
