# Generated by Django 4.2.7 on 2024-03-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0009_resource_specs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="specs",
            new_name="file",
        ),
    ]
