# Generated by Django 4.2.7 on 2024-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0010_rename_specs_resource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="resources",
            field=models.ManyToManyField(related_name="places", to="narrator.resource"),
        ),
    ]
