# Generated by Django 4.2.7 on 2024-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narrator", "0011_place_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="places", to="narrator.resource"
            ),
        ),
    ]
