version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DJANGO_DB_NAME: app
      DJANGO_DB_USER: app
      DJANGO_DB_PASSWORD: app
      DJANGO_DB_HOST: db
      DJANGO_SETTINGS_MODULE: narrator.settings
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db

volumes:
  postgres_data:
