version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DJANGO_DB_NAME: app
      DJANGO_DB_USER: app
      DJANGO_DB_PASSWORD: app
      DJANGO_DB_HOST: db
      DJANGO_SETTINGS_MODULE: narrator.settings
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      DEBUG: "true"
      DJANGO_DEBUG: "true"
      DJANGO_STATIC_URL: "/django_static/"
      DJANGO_STATIC_ROOT: "/app/django_static/"
    volumes:
      - django_static:/app/django_static
      - .:/app
    ports:
      - "9001:8000"
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.19
    ports:
      - "6006:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static:/app/django/django_static
    depends_on:
      - backend
      - frontend

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
        - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama/
    ports:
      - "11434:11434"
#  ollama-client:
#    build:
#      dockerfile: docker/ollama/Dockerfile
#    environment:
#      LLM: "mistral"
#      OLLAMA_BASE_URL: "http://ollama:11434"
#
#    depends_on:
#      - ollama

volumes:
  postgres_data:
  ollama_data:
  qdrant_data:
  django_static:
